#ifndef Enums_H
#define Enums_H

#if defined(ARDUINO)
    #include "Arduino.h"
#endif // ARDUINO


enum ChipSelectMuxId : unsigned char {
    
    CS_MUX_NONE             = 0,
    CS_MUX_RECEIVER_6_CS    = 4,
    CS_MUX_RECEIVER_5_CS    = 5,
    CS_MUX_RECEIVER_4_CS    = 6,
    CS_MUX_RECEIVER_4_LATCH = 7,
    CS_MUX_RECEIVER_3_CS    = 8,
    CS_MUX_RECEIVER_3_LATCH = 9,
    CS_MUX_RECEIVER_2_CS    = 10,
    CS_MUX_595_LATCH        = 11,
    CS_MUX_RECEIVER_2_LATCH = 12,
    CS_MUX_RECEIVER_1_CS    = 13,
    CS_MUX_RECEIVER_1_LATCH = 14
};

enum I2cChannelId : unsigned char {
    
    I2C_CHANNEL_OFF     = 0,
    I2C_CHANNEL_DEFAULT     = 2,
    I2C_CHANNEL_RECEIVER_7  = 1,
    I2C_CHANNEL_INVALID    = 0xFF
};


enum ShiftRegisterBitId : unsigned char {
    SHIFT_REGISTER_U14_BITS_OFFSET = 0,
    BIT_ID_RECEIVER_5_POWER_ON = SHIFT_REGISTER_U14_BITS_OFFSET,
    BIT_ID_RECEIVER_8_POWER_ON = SHIFT_REGISTER_U14_BITS_OFFSET + 1,
    BIT_ID_RECEIVER_7_POWER_ON = SHIFT_REGISTER_U14_BITS_OFFSET + 2,
    BIT_ID_RECEIVER_6_POWERON = SHIFT_REGISTER_U14_BITS_OFFSET + 3,
    
    SHIFT_REGISTER_U16_BITS_OFFSET = 8,
    BIT_ID_RECEIVER_4_GPIO_CH1 = SHIFT_REGISTER_U16_BITS_OFFSET + 3,
    BIT_ID_RECEIVER_4_GPIO_CH2 = SHIFT_REGISTER_U16_BITS_OFFSET + 4,
    BIT_ID_RECEIVER_4_GPIO_CH3 = SHIFT_REGISTER_U16_BITS_OFFSET + 5,
    BIT_ID_RECEIVER_4_GPIO_S1 = SHIFT_REGISTER_U16_BITS_OFFSET + 6,
    BIT_ID_RECEIVER_4_POWERON = SHIFT_REGISTER_U16_BITS_OFFSET + 7,
    
    SHIFT_REGISTER_U17_BITS_OFFSET = 16,
    BIT_ID_RECEIVER_3_GPIO_CH1 = SHIFT_REGISTER_U17_BITS_OFFSET + 3,
    BIT_ID_RECEIVER_3_GPIO_CH2 = SHIFT_REGISTER_U17_BITS_OFFSET + 4,
    BIT_ID_RECEIVER_3_GPIO_CH3 = SHIFT_REGISTER_U17_BITS_OFFSET + 5,
    BIT_ID_RECEIVER_3_GPIO_S1 = SHIFT_REGISTER_U17_BITS_OFFSET + 6,
    BIT_ID_RECEIVER_3_POWERON = SHIFT_REGISTER_U17_BITS_OFFSET + 7,

    SHIFT_REGISTER_U20_BITS_OFFSET = 24,
    BIT_ID_RECEIVER_2_GPIO_CH1 = SHIFT_REGISTER_U20_BITS_OFFSET + 3,
    BIT_ID_RECEIVER_2_GPIO_CH2 = SHIFT_REGISTER_U20_BITS_OFFSET + 4,
    BIT_ID_RECEIVER_2_GPIO_CH3 = SHIFT_REGISTER_U20_BITS_OFFSET + 5,
    BIT_ID_RECEIVER_2_GPIO_S1 = SHIFT_REGISTER_U20_BITS_OFFSET + 6,
    BIT_ID_RECEIVER_2_POWERON = SHIFT_REGISTER_U20_BITS_OFFSET + 7,

    SHIFT_REGISTER_U22_BITS_OFFSET = 32,
    BIT_ID_RECEIVER_1_GPIO_CH1 = SHIFT_REGISTER_U22_BITS_OFFSET + 3,
    BIT_ID_RECEIVER_1_GPIO_CH2 = SHIFT_REGISTER_U22_BITS_OFFSET + 4,
    BIT_ID_RECEIVER_1_GPIO_CH3 = SHIFT_REGISTER_U22_BITS_OFFSET + 5,
    BIT_ID_RECEIVER_1_GPIO_S1 = SHIFT_REGISTER_U22_BITS_OFFSET + 6,
    BIT_ID_RECEIVER_1_POWERON = SHIFT_REGISTER_U22_BITS_OFFSET + 7,
    BIT_ID_COUNT = 40
};

#endif